### ISSUE TITLE
[IDEA] Generic object to delay work

### ISSUE THREAD

**Issue by bakura10** [JouwWeb/SlmQueue#157]
Hi,

I don't know how do you handle your jobs, but I end up creating a lot of small jobs whenever an operation do more than 2 HTTP calls to other services, or when I know the task will take some time.

To that extent, I have a lot of small jobs, whose only job is simply delaying to the service layer. For instance:

``` php
class DeleteUserJob extends AbstractJob
{
     private $userService;

     public function __construct(UserService $userService)
     {
           $this->userService = $userService;
     }

     public function execute()
     {
          $this->userService->deleteUser($this->content['user_id']);
     }
}
```

I have tons of them and it's only boring to write. Couldn't we actually think of a way to make this more transparent and avoid all that boilerplate code?

I kinda like the work on Laravel and "delayed commands" (http://laravel.com/docs/5.0/bus). I'm not an expert of this bus command stuff, but it seems that each command can be decided to be delayed, by appending some kind of "delay handler".

**Comment by basz** [comment]
> Couldn't we actually think of a way  

I'm assuming you have some sort general idea?

**Comment by roelvanduijnhoven** [comment]
I'll close this one as it more than two years old. Feel free to open new issue if ideas still relevant and / or interested in fixing! :)
