### ISSUE TITLE
SlmQueue 0.5

### ISSUE THREAD

**Issue by bakura10** [JouwWeb/SlmQueue#166]
Hi everyone,

It's been a few months that SlmQueue 0.4 is out, and it's time to start working on the next version, aka 0.5 (my plan is to have 0.5 as the last version in the 0.x branch, and then going to 1.0 once we have modernized ZF components like new SM, new Event Manager... so we can start on modern foundations :)).

Here are a few features that emerged:
## Unit of Work

See #162 

Idea: as of now, SlmQueue workflow is as follow: you must retrieve a queue, and push jobs, one at a time. However this can have performance implication: if you push job at multiple places of your code, this incur as many calls to the underlying service (HTTP requests for SQS for instance).

The idea is to have a UnitOfWork (or Comitter) where jobs are inserted, and flush at the end of the request.
## Forking

See #117 
## More transparent usage

One common problem with SlmQueue is that you are forced to create jobs. Usually, jobs are small classes whose only task is to delegate the task of the actual job to a service. However, it would be awesome if we could have a more transparent way of doing that, without having to use jobs.

For instance, let's say that we have a "generateReport" method inside a service, that we'd like to delay:

``` php
class MyService
{
   public function doSomething()
   {
      // Things...

      // I WANT THIS TO BE DELAYED
      $this->generateReport();
   }

   public function generateReport()
   {
       // Generate report...
   }
}
```

Currently, delaying implies to create a GenerateReportJob, and insert it to the queue. However, it would be cool if we could do something like this:

$this->queue->delayWork([$this, 'generateReport', $parameters]);

Of course, keeping the concept of Job makes sense as in some cases it's necessary to have the additional level of abstraction, but for most small cases, it's a bit annoying. Internally, the `delayWork` method could still use a Job.

What kind of other features do you want for SlmQueue 0.5 ?

**Comment by basz** [comment]
Nog sure how this would Work. That aside - the naming is off imo. anything pushed onto a queue is by definition delayed. I see no conceptual difference between a job instance and a callable being pushed. Also, delay is an actual argument to the push method.

Discussing implementation. The push method could detect if it is a callable that is being pushed and ifso wrap it into a CallableWrapperJob or something along those lines.

A static callable would be simplest, think serializing $this onto a queue might turnout to be problemetic.

Thoughts?

**Comment by basz** [comment]
I would love it if queue and worker strategy configuration would be mergeable - makes more sense I believe. For some reason I forgot this was near impossible. Just noting it down here.

**Comment by bakura10** [comment]
Okay, in order to increase dependency of other modules, I'll tag this as 0.5 (so 0.5 is mainly a bump increase, with no feature change). Everyone's okay with that @juriansluiman @basz ?

**Comment by roelvanduijnhoven** [comment]
As we are way past 0.5 I'll close. But feel free to reopen or raise other issues if ideas from this topic still interest you @bakura10!
