### ISSUE TITLE
Abstract Queue causes fatal error when data is not unserializable

### ISSUE THREAD

**Issue by jackdpeterson** [JouwWeb/SlmQueue#174]
It appears that some of the logic in AbstractQueue.php is very sensitive to the data that can enter in from what ought to be considered a relatively untrusted source (the queue). A good example of this is if a queue can be published to by something other than SlmQueue(SQS in this case).

I'll be submitting a PR for the fix to this; however, the error is related to an invalid operand type. The fix is to do an array_merge along with some standard type checking prior to doing anything with the data['metadata'] key.

**Comment by jackdpeterson** [comment]
This can be reproduced in SlmQueueSQS by having a queue subscribed to events in AWS like an CloudWatch alert; however the logic errors are in SlmQueue. This will cause an unexpected 500 Fatal with an invalid operand type.

**Comment by roelvanduijnhoven** [comment]
Is this still a problem @jackdpeterson? Will close for now; but feel free to reopen with some details.
