### ISSUE TITLE
Best practice question surrounding connection-sensitive dependencies (e.g., database connections)

### ISSUE THREAD

**Issue by jackdpeterson** [JouwWeb/SlmQueue#177]
When using serices that rely on Doctrine ORM or otherwise on may get periodic database connection error (entity manager closed), or PDO failures if just using straight PDO. MySQL in particular kills a connection after an hour. Because SlmQueue jobs are effectively long-running php processes and _could_ be terminated using a variety of strategies (I didn't see time in there) I'm curious about what other devs are doing to ensure that connection-sensitive services are fresh and operating while keeping code as DRY as possible (not repeating the connection reset logic per-job or called method). 

A few questions for discussion:
1. Where are folks placing connection detection / close / re-open logic?
2. How has your strategy worked overall in terms of stability and/or performance impacts with the reset logic?

based on the output of this open issue, I'll create a PR to document the discussed 'best practice' because I think it's relevant to anyone who's in a discovery process / testing out implementing this module in a test / production environment.

**Comment by basz** [comment]
I published this module https://github.com/bushbaby/BsbDoctrineReconnect which does the job

**Comment by jackdpeterson** [comment]
I love this. I may also add a reference to this in https://github.com/jackdpeterson/ImmutableStateStatusTracker module -- which currently uses a ping() and reconnect method to restore connections. This approach seems a little cleaner.

**Comment by jackdpeterson** [comment]
I'll keep this open a little longer for aggregating some other (non-doctrine-specific areas). Thinking about this, while I use Doctrine -- and many other ZF2ers do as well, it's not the only kid on the block. So I'll keep this open until we have some other answers for non-Doctrine users. @basz, your answer is perfect for doctrine folks and I'm testing it out locally right as I type this.

**Comment by psychowico** [comment]
hey. I use basic zf2 `Zend\Db\...` interface - driver directly and `AbstractTableGateway`. My solution for this problem is simple abstraction - I created `BaseJob` class that extend `SlmQueue\Job\AbstractJob`. Then I override `execute` function.

```php
use Zend\Db\Adapter\Exception\InvalidQueryException;

...

try {
    // function run is abstract here and should be override in child classes,
    // instead of `run` function
    $this->run();
} catch (InvalidQueryException $e) {
    if ($e->getCode() == /*server has gone away*/ 0) {
        $this->log('SQL connection lost detected. Reconnecting.');
        $adapter = $this->getServiceLocator()->get('Zend\Db\Adapter\Adapter');
        // some magic code to reconnect to SQL in zf2
        $driver     = $adapter->getDriver();
        $connection = $driver->getConnection();
        $connection->disconnect();
        $driver->registerConnection($connection->connect());
        if($connection->isConnected()) {
            // call run function again, now with working connection
            return $this->run();
        }
    }
    throw $e;
}
```

This code was simplified.
This solution have small potential problem. If our job make storing some state in diffrent place that database (e.g. redis). It is possible that redis store is done and then we got sql error and run job again. Then redis store will be doubled.

I haven't any jobs like that, so for me this solution was enough.

**Comment by jackdpeterson** [comment]
Another (heavy handed) approach would be:

```
 $startTime = time();
        
        $eventManager->getSharedManager()->attach(WorkerInterface::class, WorkerEvent::EVENT_PROCESS_IDLE, function (WorkerEvent $e) use($startTime) {
            if (time() - $startTime >= 1800) {
                syslog(LOG_INFO, 'exiting after being idle for 30 minutes. Expecting supervisor to restart me.');
                $e->exitWorkerLoop();
            }
        }, - 1000);```

to choke out the worker *BEFORE* a timeout would typically occur.

**Comment by roelvanduijnhoven** [comment]
@jackdpeterson Are you still using this repo? And if so: how did you end up fixing this? Maybe we should include some words of advise or provide default configuration that will make sure that working with databases is no problem out of the box.

In the upcoming release we will include a strategy that limits the time a worker may live. So that may definitely help.

**Comment by jackdpeterson** [comment]
I set up supervisord and configured jobs to kill after X amount of time and auto-restart the jobs. That was the simplest solution at that point in time.

**Comment by jackdpeterson** [comment]
To answer your other question, I do have a project that is actively using SlmQueue. That being said, I’ve been transitioning most of my projects over to Slim and away from the ZF ecosystem.

**Comment by roelvanduijnhoven** [comment]
Thanks. Some work is done recently to make this lib usable without having ZF. Not sure how easy that is though. But you could give it a show when you find yourself in need of some new project.

Anyway; we will update the docs soon with some FAQ / tips when working with long connectivity and some hints how to solve them.

**Comment by MatthiasKuehneEllerhold** [comment]
@jackdpeterson said: 
> MySQL in particular kills a connection after an hour.

According to the docs the default values for this is 8 hours. (See [MySQL Docs](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_interactive_timeout) "connect_timeout", "wait_timeout" and "interactive-timeout"). 
Can you confirm that you've changed these options or does MySQL kill connections after 1 hour despite configured to wait 8 hours? I've had problem with that awhile back, but dont know if we used the default value...

**Comment by jackdpeterson** [comment]
For our application extending the wait time wasn’t an option. The easiest approach in our case was to use one of the methods mentioned above — have an in-process timer running (safest) or have the process die midway through and re-run through the queue redelivery methods. All jobs should be engineered to be able to safely rerun anyways as a core assumption.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by roelvanduijnhoven** [comment]
I'll close this issue. With work of @MatthiasKuehneEllerhold  on https://github.com/JouwWeb/SlmQueue/pull/214 this is improved!
