### ISSUE TITLE
Genericize the SlmQueue project into the non-ZF bits and the ZF-required bits for broader adoption

### ISSUE THREAD

**Issue by jackdpeterson** [JouwWeb/SlmQueue#199]
Currently, the implementation of SlmQueue appears tightly coupled to the whole ZF Event Manager side of things. Making this project generic would make these abstractions more useful across a broader set of PHP projects (e.g., very lean PSR-7-driven APIs).

Is this something that's currently under consideration for this project at this point in time?

My initial thoughts would be to expose interfaces that must be implemented (similar to how League approaches the OAuth2 implementation) -- example project: https://oauth2.thephpleague.com/

The benefit of this approach is that the integration details could be exposed as interfaces and direct attachment into something like ZF would be an event-manager binding mechanism ... but for other projects one could implement their own bindings as it is appropriate.

**Comment by basz** [comment]
It's not considered at the moment, but your points are valid. That said it is possible to use this module outside an zend framework MVC application. Myself is using it in an expressive application without any problems. I only needed to recreate a cli command to start the doctrine queue.

I would like to see a more generic v2 version. PHP 7 only. Unfortunately I simply don't have the time to do that... About refactoring to something that doesn't have events I not so sure. We wanted to make something evented and the zf event manager was a natural fit and a good tool available within the zf eco system. It got the job done. My current application doesn't use the zf event manager any other way, but has it's own implementation for the most part. Do we care?

**Comment by jackdpeterson** [comment]
Well, to be honest ... I've gone away from the event-driven system style of development for much of my backend development these days. I find being more explicit in my code has led to more sane debugging processes and provides for more coherence for folks who are also picking up a new microservice I'm working on or otherwise. So to me the Event-driven side of things is less than useful / ideal. Others may disagree, of course ... but after working in the WP ecosystem which is events on steroids IMHO ... I no longer wish to have much to do with events unless I have a very specific business case for doing so.

**Comment by basz** [comment]
I agree, events can be hell to debug. But to change something that works for the sake of change, no at this time. 
However I encourage you to come up with a different solution if you require one for v2... :-)

**Comment by svycka** [comment]
@basz maybe you can share code how you implemented this in zend-expressive? would be great help :) its not that simple as just writing console commands. I hope you did this with symfony/console but that's not that important.

**Comment by basz** [comment]
https://gist.github.com/basz/6411860cd72404543e39a325ece328e5

**Comment by basz** [comment]
I think that's it. Scanning my source quickly I don't believe you need to do much more (besides adding the config to autoload). Ofcourse the controller plugins won't work

**Comment by svycka** [comment]
hmm what you did with this https://github.com/juriansluiman/SlmQueue/blob/a4f09a1c4dece7fd2d94498249affb8dea7e07b1/src/Factory/WorkerFactory.php#L25 this event manager is configured in zend-mvc but I guess we could just do `new EventManager()` no or I will have to create alias for this?

**Comment by basz** [comment]
i see what you mean;

I have this in my config/container.php

```
$config      = require __DIR__ . '/config.php';
$container   = new ServiceManager($config['dependencies']);
$mvcServices = new ServiceManagerConfig();

$mvcServices->configureServiceManager($container);
$container->setAlias('Config', 'config');
$container->setAlias('Configuration', 'config');
$container->setService('config', $config);

return $container;
```

**Comment by svycka** [comment]
so I have to have zend-mvc as dependancy? :(

**Comment by basz** [comment]
I'm sorry I knee deep in some other stuff; I guess what you need is an implementation of EventManagerInterface. I don't *think* it needs to come from the (mvc) service locator. There is no event messaging outside of the packages. `new EventManager` should do. Are you planning on removing the dependency? In my current project I just live with it even while its a expressive app and nothing else uses it...

**Comment by svycka** [comment]
I am thinking maybe its possible to do it in this module create new eventmanager instead of getting it from service manager would it introduce any BC break?

**Comment by basz** [comment]
I think in general it is not a problem and only a breaking change for anyone who is listening to events through the 'global' event listener.

Not sure who or why does that

**Comment by svycka** [comment]
I have created PR for this https://github.com/juriansluiman/SlmQueue/pull/201

**Comment by roelvanduijnhoven** [comment]
@svycka The PR got merged. It is now (kinda?) usuable without ZF. Should we close this issue? Or are there tasks pending still?

**Comment by svycka** [comment]
@roelvanduijnhoven there is one https://github.com/JouwWeb/SlmQueue/pull/202 PR but I guess we can close this
