### ISSUE TITLE
RabbitMQ support

### ISSUE THREAD

**Issue by chris1312** [JouwWeb/SlmQueue#217]
Are there any known RabbitMQ adapter-modules for SlmQueue?

**Comment by basz** [comment]
not that I'm aware of no. wold be nice to have though ;-)

**Comment by roelvanduijnhoven** [comment]
I'll mark as an enhancement :). Feel free to contribute @chris1312.

**Comment by aurum86** [comment]
Hi, we have rnd-cosoft/slm-queue-rabbitmq in Packagist: https://packagist.org/packages/rnd-cosoft/slm-queue-rabbitmq
It has its first major version and ready to be used. :) Could this be added in SLM readme as a suggested package for RabbitMQ ?

**Comment by roelvanduijnhoven** [comment]
@roelvanduijnhoven Sure!

Feel free to send in a PR. I'll happily merge :heart:

**Comment by roelvanduijnhoven** [comment]
Thank you @aurum86!
