### ISSUE TITLE
zend-component-installer compatibility is incorrect

### ISSUE THREAD

**Issue by boesing** [JouwWeb/SlmQueue#218]
You have to change the `module` entry within `composer.json` to `SlmQueue` instead of `SlmQueue\Module` as you have to provide the module name instead of the FQCN to the `Module` class.

Pull Request is already created by @TomHAnderson in #216

**Comment by roelvanduijnhoven** [comment]
Excuse me for our my late reaction @boesing. Apparently I didn't watch this repo; and thus missed any updates to it. Merged the PR of @TomHAnderson; thanks both of you! I have published a new minor release.
