### ISSUE TITLE
issue in insert into the queue

### ISSUE THREAD

**Issue by abdullah-aghayan** [JouwWeb/SlmQueue#219]
I have had problem with insert in to queue which when I start job so I can't insert into queue anymore but when job not working(stop) it's inserted correctly 
Do you know what I should do?

**Comment by basz** [comment]
Do I understand you when you say;

When a job is running you are unable to is insert new jobs?

If so; that is strange. Job insertion and job execution are not related.

- What error do you get, if any?
- Which SlmQueue adapter are you using?

**Comment by abdullah-aghayan** [comment]
I use Doctrine adapter but I don't detect any error during run time.
The point is in my local it's working correctly but in server it dosen't work with the same configuration.

**Comment by basz** [comment]
I can only advise you to do some debuging in the Queue class’es push method unless you provide more information.

**Comment by abdullah-aghayan** [comment]
I think my problem is put job command in cron job in following way so it's not working correctly .
`run-one php public/index.php queue doctrine import --start`
Do you have any idea how can I run  it on server which still running any time?

**Comment by basz** [comment]
Running via cron should work. Although supervisor or similar is recommended.

See: https://github.com/JouwWeb/SlmQueue/blob/master/docs/7.WorkerManagement.md

**Comment by roelvanduijnhoven** [comment]
I'll close this issue for now. Once you have more information; feel free to re-open.
