### ISSUE TITLE
zendframework -> laminas

### ISSUE THREAD

**Issue by iwyg** [JouwWeb/SlmQueue#223]
Hi there!
Are there any plans porting this project to the laminas namespace, and if so, do you need help?

Kind Regards

**Comment by roelvanduijnhoven** [comment]
No plans yet @iwyg. But absolutely interested in migrating! If you would be so kind to help us on this, please be my guest, and tag me if you need any help or reviews.

I tagged this issue as enhancement.

**Comment by basz** [comment]
see https://github.com/JouwWeb/SlmQueue/pull/225
