### ISSUE TITLE
What to do before 2.x?

### ISSUE THREAD

**Issue by roelvanduijnhoven** [JouwWeb/SlmQueue#227]
The latest work on Laminas and the bump to PHP >= 7.2 will require a major bump to 2.x. 

A good moment to ask ourselves: is there other stuff we want to deprecate or remove at this point? 

Do you have thoughts on this @basz, @bakura10?

@bakura10 I also asked you, as you are listed as contributor to this repo at this point :).

**Comment by basz** [comment]
these come to mind

- deprecate laminas-mvc controller commands, in favour of Symfony commands (see https://github.com/JouwWeb/SlmQueueDoctrine/issues/150)
- remove support for laminas-service-manager v2 in factories (https://github.com/JouwWeb/SlmQueueDoctrine/blob/master/src/Factory/DoctrineWorkerControllerFactory.php#L31)

**Comment by roelvanduijnhoven** [comment]
@basz 

> remove support for laminas-service-manager v2 in factories 

I removed the old style factories today!

> deprecate laminas-mvc controller commands, in favour of Symfony commands (see JouwWeb/SlmQueueDoctrine#150)

This repo does not use console at all, right? But I agree we can do that in the bump from SlmQueue to SlmQueueDoctrine :).

> ticks

Dropped comment in that issue.

> buryable/releaseable

That would indeed require a major bump. As would https://github.com/JouwWeb/SlmQueue/issues/17. But the gains are also very minimal if you ask me. If you want to do it, feel free, and we can postpone the release. But otherwise I propose we don't block the release on this issue.

Thanks a lot!

**Comment by basz** [comment]
> But otherwise I propose we don't block the release on this issue.

👍

**Comment by roelvanduijnhoven** [comment]
Feel free to :ship: @basz. Can do it as well, but since you did the heavy lifting :).
