### ISSUE TITLE
MVC is required

### ISSUE THREAD

**Issue by internalsystemerror** [JouwWeb/SlmQueue#231]
https://github.com/JouwWeb/SlmQueue/blob/d59a3b47ec44cb8f3bc1b861cf5d3c6509b54cc4/src/ServiceManager/AbstractPluginManager.php#L5

The above referenced line requires the installation of laminas/laminas-mvc. Is this interface required? I'm using Mezzio (previously Zend Expressive) and trying to use this library so I don't use Laminas MVC.

**Comment by roelvanduijnhoven** [comment]
@internalsystemerror We provide a Plugin for Laminas controllers in this repo. That one _does_ depend on MVC.

But you are correct that the code you reference should not have to depend on laminas MVC. I created PR https://github.com/JouwWeb/SlmQueue/pull/232 to address this.

Once lights are green I'll ship a new release.

**Comment by roelvanduijnhoven** [comment]
Fixed in https://github.com/JouwWeb/SlmQueue/issues/231. Released a new version.
