### ISSUE TITLE
SLM v3 as stable version

### ISSUE THREAD

**Issue by chris1312** [JouwWeb/SlmQueue#242]
Hi all,
Current v3 version is still marked as beta and there is no Issue for it making it stable.
Are there any development planned to make it stable apart from testing it? @roelvanduijnhoven

**Comment by roelvanduijnhoven** [comment]
@chris1312 Yes there is. We are migrating our own system to the latest PHP version. And as part of that, we will need some work on this repo as well. So _hopefully_ this should all be done within the next 4 weeks or so.

But.. feel free to address a PR if you want to move faster!

**Comment by trylika** [comment]
What is current situation with v3 and PHP8 support? is there anything to help for release?

**Comment by roelvanduijnhoven** [comment]
Can we safely drop the beta @koenkivits  :)?

**Comment by koenkivits** [comment]
@roelvanduijnhoven not yet! It still needs a bit of work:

- [ ] move the `laminas-cli` integration from SlmQueueDoctrine to this repository (so other adapters can use it)
- [ ] update the documentation (as the CLI will change)
- [ ] write a small migration guide

It shouldn't be too much work; I'll try to get a final version out this week. :) (cc @trylika)

**Comment by trylika** [comment]
@koenkivits if you'll need any help, i.e. testing how/if it works, ping me :) 
our project uses this library and we are looking to upgrade from PHP7.4 to PHP8.0

**Comment by koenkivits** [comment]
@trylika thanks for the offer! Can I ask you which adapter you're using? :)

I've just created PRs for `SlmQueue` and `SlmQueueDoctrine` by the way:

* https://github.com/JouwWeb/SlmQueue/pull/243
* https://github.com/JouwWeb/SlmQueueDoctrine/pull/170

**Comment by trylika** [comment]
@koenkivits in an odd coincidence - we are using `SlmQueueDoctrine` :)

**Comment by koenkivits** [comment]
@trylika then you should now be able to upgrade to the latest version for PHP8 support. :)

Both `SlmQueue` and `SlmQueueDoctrine` now have an `UPGRADE.md`, which contains upgrade instructions for the current major release:

* https://github.com/JouwWeb/SlmQueueDoctrine/blob/4.0.0/UPGRADE.md
* https://github.com/JouwWeb/SlmQueue/blob/3.0.0/UPGRADE.md

I hope this is enough to get everyone up-to-date. Please let us know if you still find issues!
